services:
  monitor:
    build:
      args:
        ENERGI_VERSION: ${ENERGI_VERSION}
      context: nodemon
    depends_on:
      - core
    env_file: nodemon/.env
    environment:
      - TERM=xterm
    image: energi-nodemon:${ENERGI_VERSION}-1.1.2-0.0
    restart: unless-stopped
    volumes:
      - core-data:/home/nrgstaker/.energicore3
      - monitor-data:/var/multi-masternode-data/nodebot
      - monitor-logs:/home/nrgstaker/log

volumes:
  monitor-data:
  monitor-logs:
